# Generated by Django 3.2.13 on 2022-05-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20220513_2105"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/sample.jpg", null=True, upload_to=""
            ),
        ),
    ]
