version: "3"

services:
  pg_database:
    container_name: proshop_db
    build: ./services/postgres
    restart: always
    env_file:
      - services/.envs/.pg.env
    volumes:
      - ./services/postgres/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pg_admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - services/.envs/.pgadmin.env
    ports:
      - "5050:80"

  backend:
    container_name: django
    build: ./services/backend
    env_file:
      - ./services/.envs/.env.development.local
      - ./services/.envs/.pg.env
    # command: python manage.py runserver
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./services/backend/:/usr/src/app/
    # ports:
    #   - "8000:8000"
    expose:
      - 8000
    depends_on:
      - pg_database

  nginx:
    container_name: nginx
    build: ./services/nginx
    ports:
      - "1337:80"
    depends_on:
      - backend
