version: "3"

services:
  proshop_db:
    build: ./services/postgres
    restart: always
    env_file:
      - ./services/postgres/.pg.env
    volumes:
      - ./services/postgres/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pg_admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./services/postgres/.pgadmin.env
    ports:
      - "5050:80"
